server:
  port: 8002
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 192.168.29.128
      port: 6379
      password: 123456